# Generated by Django 5.1.7 on 2025-04-02 10:51

from django.db import migrations, models

import education.validators


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[education.validators.validate_video_link],
                verbose_name="Video link",
            ),
        ),
    ]
