# Generated by Django 5.1.7 on 2025-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_alter_lesson_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, null=True, verbose_name="Video link"),
        ),
    ]
